version: 2
jobs:
  build:
    docker:
      - image: yusukeiwaki/chromiumos_builder
    working_directory: /chromiumos
    environment:
      GIT_COMMITTER_NAME: CircleCI
      GIT_COMMITTER_EMAIL: circleci@example.com
      GIT_AUTHOR_NAME: CircleCI
      GIT_AUTHOR_EMAIL: circleci@example.com
    steps:
      - run:
          name: repo init
          command: echo y | repo init -u https://chromium.googlesource.com/chromiumos/manifest.git --repo-url https://chromium.googlesource.com/external/repo.git
      - run:
          name: repo sync
          command: repo sync
      - run:
          name: build
          command: |
            cros_sdk -- ./build_packages --board=${BOARD}
            cros_sdk -- ./build_image --board=${BOARD}
            cros_sdk -- cros flash --board=${BOARD} file:///chromiumos/chromiumos.iso
